=encoding iso-8859-1

=head1 NOM

perlfaq - Foire aux questions sur Perl (Date: 1999/05/23 20:38:02)

=head1 DESCRIPTION

Ce document est découpé de la manière suivante :

=over

=item perlfaq: Description de la structure de la FAQ.

Ce document.

=item L<perlfaq1>: Questions Générales sur Perl.

Informations très générales sur Perl.

=over 4

=item * Qu'est ce que Perl ? 

=item * Qui supporte Perl ? Qui le développe ? Pourquoi est-il gratuit ? 

=item * Quelle version de Perl dois je utiliser ? 

=item * Qu'est-ce que perl4 et perl5 ? 

=item * Qu'est-ce que perl6 ? 

=item * Est-ce que Perl est stable ? 

=item * Est-il difficile d'apprendre Perl ? 

=item * Est-ce que Perl tient la comparaison avec d'autres langages comme
Java, Python, REXX, Scheme ou Tcl ?

=item * Que puis-je faire avec Perl ? 

=item * Quand ne devrais-je pas programmer en Perl ? 

=item * Quelle est la différence entre "perl" et "Perl" ? 

=item * Parle-t-on de programme Perl ou de script Perl ? 

=item * Qu'est ce qu'un JAPH ? 

=item * Où peut on trouver la liste des mots d'esprit de Larry Wall ? 

=item * Comment convaincre mon administrateur système/chef de projet/employés
d'utiliser Perl5 plutot qu'un autre langage ?

=back

=item L<perlfaq2>: Obtenir et Apprendre Perl.

Où trouver les sources et la documentation de Perl.

=over 4

=item * Quelles machines supportent Perl ? Où puis-je trouver Perl ?

=item * Comment trouver une version binaire de Perl ?

=item * Je n'ai pas de compilateur C sur mon système. Comment puis-je compiler
perl ?

=item * J'ai copié le binaire Perl d'une machine sur une autre mais les
scripts ne fonctionnent pas.

=item * J'ai récupéré les sources et j'essaie de les compiler mais
gdbm/dynamic loading/malloc/linking/... échoue. Comment faire pour que ça
marche ?

=item * Quels sont les modules et extensions qui existent pour Perl ?
Qu'est-ce que CPAN ? Que signifie CPAN/src/... ?

=item * Existe-t-il une version de Perl certifiée ISO ou ANSI ?

=item * Où puis-je trouver des informations sur Perl ?

=item * Quels sont les groupes de discussion concernant Perl sur Usenet ? Où
puis-je poser mes questions ?

=item * Où puis-je poster mon code source ?

=item * Les livres sur Perl

=item * Les magazines sur Perl

=item * Perl sur Internet : accès via FTP et WWW

=item * Quelles sont les listes de diffusion concernant Perl ?

=item * Archives de comp.lang.perl.misc

=item * Où puis-je acheter une version commerciale de Perl ?

=item * Où dois-je poster mes rapports de bugs ?

=item * Qu'est-ce que perl.com ? Les Perl Mongers ? pm.org ? perl.org ?

=back

=item L<perlfaq3>: Outils de Programmation.

Outils pour le programmeur et support technique.

=over 4

=item * Comment fais-je pour... ?

=item * Comment utiliser Perl de façon interactive ?

=item * Y a-t-il un shell Perl ?

=item * Comment debugger mes programmes Perl ?

=item * Comment connaître la vitesse d'exécution de mes programmes Perl ?

=item * Comment faire une référence croisée de mon programme Perl ?

=item * Y a-t-il un outil de mise en page de code Perl ?

=item * Y a-t-il un ctags pour Perl ?

=item * Existe-t-il un environnement de développement intégré ou un Éditeur
Perl sous Windows ?

=item * Où puis-je trouver des macros pour Perl sous vi ?

=item * Où puis-je trouver le mode perl pour emacs ?

=item * comment utiliser des 'curses' avec Perl ?

=item * Comment puis-je utiliser X ou Tk avec Perl ?

=item * Comment générer de simples menus sans utiliser CGI ou Tk ?

=item * Qu'est ce que undump ?

=item * Comment faire en sorte que mes programmes Perl soient plus rapides ?

=item * Comment faire pour que mes programmes Perl prennent moins de mémoire ?

=item * Est-ce sûr de retourner un pointeur sur une données locale ?

=item * Comment puis-je libérer un tableau ou table de hachage pour réduire
mon programme ?

=item * Comment rendre mes scripts CGI plus efficaces ?

=item * Comment dissimuler le code source de mon programme Perl ?

=item * Comment compiler mon programme Perl en code binaire ou C ?

=item * Comment compiler Perl pour en faire du Java ?

=item * Comment faire fonctionner #!perl sur [MS-DOS,NT,...] ?

=item * Puis-je écrire des programmes Perl pratiques sur la ligne de commandes
?

=item * Pourquoi les commandes Perl à une ligne ne fonctionnent-elles pas sur
mon DOS/Mac/VMS ?

=item * Où puis-je en apprendre sur la programmation CGI et Web en Perl ?

=item * Où puis-je en apprendre sur la programmation orientée objet en Perl ?

=item * Où puis-je en apprendre sur l'utilisation liée du Perl et du C ?
[h2xs, xsubpp]

=item * J'ai lu perlembed, perlguts, etc., mais je ne peux inclure du perl
dans mon programme C, qu'est ce qui ne va pas ?

=item * Quand j'ai tenté d'exécuter mes scripts, j'ai eu ce message. Qu'est ce
que cela signifie ?

=item * Qu'est-ce que MakeMaker ?

=back

=item L<perlfaq4>: Manipulation de Données.

Comment manipuler les nombres, les dates, les chaines de caractères, les
tableaux, les tableaux H-codés et autres renseignements sur les types.

=over 4

=item * Pourquoi est-ce que j'obtiens des nombres décimaux longs
(e.g.. 19.9499999999999) à la place du nombre que j'attends (e.g. 19.95) ?

=item * Pourquoi mon nombre octal n'est-il pas interprété correctement ?

=item * Est-ce que perl a une fonction round() ? Et qu'en est-il de ceil()
(majoration) et floor() (minoration) ? Et des fonctions trigonométriques ?

=item * Comment est-ce que je convertis des bits en entiers ?

=item * Pourquoi & ne fonctionne-t-il pas comme je le veux ?

=item * Comment puis-je multiplier des matrices ?

=item * Comment puis-je effectuer une opération sur une série d'entiers ?

=item * Comment puis-je produire des chiffres romains ?

=item * Pourquoi mes nombres aléatoires ne sont-ils pas aléatoires ?

=item * Où trouver la semaine/le jour de l'année ?

=item * Comment trouver le siècle ou le millénaire actuel ?

=item * Comment puis-je comparer deux dates ou en calculer une différence ?

=item * Comment puis-je convertir une chaîne de caractères en secondes depuis
l'origine ?

=item * Comment trouver le jour du calendrier Julien ?

=item * Comment trouver la date d'hier ?

=item * Est-ce que Perl a un problème avec l'an 2000 ? Est-ce Perl est
compatible an 2000 ?

=item * Comment m'assurer de la validité d'une entrée ?

=item * Comment enlever les caractères d'échappement d'une chaîne de
caractères ?

=item * Comment enlever des paires de caractères successifs ?

=item * Comment effectuer des appels de fonction dans une chaîne ?

=item * Comment repérer des éléments appariés/imbriqués ?

=item * Comment inverser une chaîne de caractères ?

=item * Comment développer les tabulations dans une chaîne de caractères ?

=item * Comment remettre en forme un paragraphe ?

=item * Comment accéder ou/modifier les N premières lettres d'une chaîne de
caractères ?

=item * Comment changer la n-ième occurrence de quelque chose ?

=item * Comment compter le nombre d'occurrences d'une sous-chaîne dans une
chaîne de caractères ?

=item * Comment mettre en lettres majuscules tous les mots d'une ligne ?

=item * Comment découper une chaîne séparée par un [caractère] sauf à
l'intérieur d'un [caractère] ? (Champs délimités par des virgules)

=item * Comment supprimer des espaces blancs au début/à la fin d'une chaîne ?

=item * Comment cadrer une chaîne avec des blancs ou un nombre avec des zéros
?

=item * Comment extraire une sélection de colonnes d'une chaîne de caractères
?

=item * Comment calculer la valeur soundex d'une chaîne ?

=item * Comment interpoler des variables dans des chaînes de texte ?

=item * En quoi est-ce un problème de toujours mettre "$vars" entre
guillemets ?

=item * Pourquoi est-ce que mes documents <<INSERE ne marchent pas ?

=item * Quelle est la différence entre une liste et un tableau ?

=item * Quelle est la différence entre $array[1] et @array[1] ?

=item * Comment puis-je supprimer les doublons d'une liste ou d'un tableau ?

=item * Comment puis-je déterminer si une liste ou un tableau contient un
certain élément ?

=item * Comment puis-je calculer la différence entre deux tableaux ? Comment
puis-je calculer l'intersection entre deux tableaux ?

=item * Comment tester si deux tableaux ou hachages sont égaux ?

=item * Comment puis-je trouver le premier élément d'un tableau pour lequel
une proposition est vraie ?

=item * Comment puis-je gérer des listes chaînées ?

=item * Comment puis-je gérer des listes circulaires ?

=item * Comment puis-je mélanger un tableau au hasard ?

=item * Comment puis-je traiter/modifier chaque élément d'un tableau ?

=item * Comment puis-je sélectionner un élément aléatoire d'un tableau ?

=item * Comment permuter N éléments d'une liste ?

=item * Comment trier un tableau par (n'importe quoi) ?

=item * Comment puis-je manipuler des tableaux de bits ?

=item * Pourquoi est-ce que defined() retourne vrai sur des tableaux et
hachages vides ?

=item * Comment puis-je traiter un tableau entier ?

=item * Que se passe-t-il si j'ajoute ou j'enlève des clefs d'un hachage
pendant que j'itère dessus ?

=item * Comment puis-je rechercher un élément d'un hachage par sa valeur ?

=item * Comment puis-je savoir combien d'entrées sont dans un hachage ?

=item * Comment puis-je trier un hachage (en option: par valeur plutôt que par
clef) ?

=item * Comment puis-je conserver mes hachages toujours ordonnés ?

=item * Quel est la différence entre "delete" et "undef" pour des hachages
?

=item * Pourquoi est-ce que mes hachages attachés ne font pas la distinction
entre exists et defined ?

=item * Comment remettre à zéro une opération each() à mi-chemin ?

=item * Comment puis-je obtenir l'unicité des clefs de deux hachages ?

=item * Comment puis-je enregistrer un tableau multidimensionnel dans un
fichier DBM ?

=item * Comment puis-je faire en sorte que mon hachage conserve l'ordre des
éléments que j'y mets ?

=item * Pourquoi est-ce que de passer à une sous-routine un élément non défini
d'un hachage le crée du même coup ?

=item * Comment puis-je faire l'équivalent en Perl d'une structure en C, d'une
classe/d'un hachage en C++ ou d'un tableau de hachages ou de tableaux ?

=item * Comment puis-je utiliser une référence comme clef d'un hachage ?

=item * Comment puis-je manipuler proprement des données binaires ?

=item * Comment puis-je déterminer si un scalaire est un nombre/entier/à
virgule flottante ?

=item * Comment puis-je conserver des données persistantes entre divers appels
de programme ?

=item * Comment puis-je imprimer ou copier une structure de données récursive
?

=item * Comment puis-je définir des méthodes pour toutes les classes ou tous
les objets ?

=item * Comment est-ce que je vérifie la somme de contrôle d'une carte de
crédit ?

=item * Comment compacter des tableaux de nombres à virgule flottante simples
ou doubles pour le code XS ?

=back

=item L<perlfaq5>: Fichiers et Formats.

Entrées/Sorties et tout ce qui se rapporte aux fichiers : descripteur de
fichier, vidage du buffer, formats et mise en page.

=over 4

=item * Comment vider/annuler les tampons en sortie ? Pourquoi m'en soucier ?

=item * Comment changer une ligne/effacer une ligne/insérer une ligne au
milieu/ajouter une ligne en tête d'un fichier ?

=item * Comment déterminer le nombre de lignes d'un fichier ?

=item * Comment créer un fichier temporaire ?

=item * Comment manipuler un fichier avec des enregistrements de longueur fixe
?

=item * Comment rendre un descripteur de fichier local à une routine ? Comment
passer ce descripteur à d'autres routines ? Comment construire un tableau de
descripteurs ?

=item * Comment utiliser un descripteur de fichier indirectement ?

=item * Comment mettre en place un pied-de-page avec write() ?

=item * Comment rediriger un write() dans une chaîne ?

=item * Comment afficher mes nombres avec des virgules pour délimiter les
milliers ?

=item * Comment traduire les tildes (~) dans un nom de fichier ?

=item * Pourquoi les fichiers que j'ouvre en lecture-écriture ont-ils leur
contenu effacé en premier lieu ?

=item * Pourquoi ai-je l'erreur "Argument list too long" avec <*> de temps en
temps ?

=item * Y a-t-il une fuite / un bug avec glob() ?

=item * Commend ouvrir un fichier dont le nom commence par "E<gt>" ou avec des
espaces en fin ?

=item * Comment renommer un fichier de façon sûre ?

=item * Comment verrouiller un fichier ?

=item * Pourquoi ne pas faire simplement C<open(FH, "E<gt>file.lock")> ?

=item * Je ne comprends toujous pas le verrouillage. Je veux seulement
incrémenter un compteur dans un ficher. Comment faire ?

=item * Comment modifier un fichier binaire directement ?

=item * Comment recupérer l'estampille temporelle d'un fichier en perl ?

=item * Comment imprimer une estampille temporelle sur un fichier en perl ?

=item * Comment écrire dans plus d'un fichier en même temps ?

=item * Comment lire tout un fichier d'un seul coup ?

=item * Comment lire un fichier paragraphe par paragraphe ?

=item * Comment lire un seul caractère d'un fichier ? Et du clavier ?

=item * Comment savoir si un caractère est disponible sur un descripteur ?

=item * Comment écrire un tail -f en perl ?

=item * Comment faire un dup() sur un descripteur en Perl ?

=item * Comment fermer un descripteur connu par son numéro ?

=item * Pourquoi "C:\temp\foo" n'indique pas un fichier DOS ? Et même
"C:\temp\foo.exe" ne marche pas ?

=item * Pourquoi C<glob("*.*")> ne donne-t-il pas tous les fichiers ?

=item * Pourquoi Perl me laisse effacer des fichiers protégés en écriture ?
Pourquoi -i écrit dans des fichiers protégés ? N'est-ce pas un bug de Perl ?

=item * Comment sélectionner une ligne au hasard dans un fichier ?

=item * Pourquoi obtient-on des espaces étranges lorsqu'on affiche un tableau
de lignes ?

=back

=item L<perlfaq6>: Expressions Régulières.

Recherche de motif et expressions régulières.

=item L<perlfaq7>: Questions générales sur le langage Perl.

Questions sur le langage Perl qui ne rentrent dans aucun des chapitres
précédents.

=item L<perlfaq8>: Interaction avec le système.

Communication inter-processus (IPC), interface homme-machine (clavier,
écran, souris).

=item L<perlfaq9>: Programmation réseau.

Programmation réseau, l'Internet et quelques lignes sur le web.

=back

=head2 Où se procurer ce document.

La version originale de ce  document est régulièrement postée dans 
comp.lang.perl.announce et dans plusieurs autres groupe de discussions. 
Il est disponible sous plusieurs formats au CPAN dans le répertoire 
/CPAN/doc/FAQs/FAQ/, et sur le web à l'adresse 
http://www.perl.com/perl/faq/ .

La version française est disponible sur le site officiel des traducteurs
http://perl.enstimac.fr/ .

=head2 Comment contribuer à ce document.

Les ajouts et les suggestions pour la version originale doivent être
adressés à perlfaq-suggestions@perl.com. Les corrections et les ajouts
à la version française doivent être adressés à 
perlfrench@immortels.frmug.org .
Si vous voulez participer à l'effort de traduction et de relecture vous
pouvez vous inscrire à la mailing-liste perlfrench en envoyant un message
à Majordomo@frmug.org contenant la ligne
subscribe perlfrench

Ces adresses ne doivent pas être utilisés pour I<poser> des questions.
Elles sont destinées à la correction de la FAQ en cours.

=head2 Que va-t-il se passer si vous envoyez votre question aux auteurs.

Votre question sera probablement pas lue, à moins qu'elle représente une
suggestion d'ajout à la FAQ, qui de toute manière aurait dû être 
adressée à perlfaq-suggestions@perl.com .

Vous feriez mieux de lire le chapitre 2 de cette faq. Vous auriez appris
que fr.comp.lang.perl et comp.lang.perl sont les endroits les plus 
appropriés pour poser vos questions. 
Si votre question est vraiment très important et qu'il vous
faut une réponse immédiate, vous feriez mieux d'engager un consultant.

Attention même si vous utilisez Perl pour écrire des scripts CGI, les 
questions portant sur la configuration des différents logiciels de 
serveurs web, sur l'utilisation des protocoles CGI et du HTML n'ont rien
à faire sur fr.comp.lang.perl . Le groupe de discussion le plus 
approprié pour les problèmes CGI est fr.comp.infosystemes.www.auteurs. 

Il est fortement conseillé de lire la charte du groupe avant de poster
la première fois, elle contient de bons conseils pour une bonne entente
sur ce groupe de discussion. La charte est postée régulièrement sur le 
groupe de discussion et est aussi disponible dans fr.usenet.reponses et 
sur http://usenet-fr.news.eu.org/liste-groupes.html

=head1 Credits de Tom Christiansen

Lorsque j'ai commencé l'écriture de la FAQ Perl à la fin des années 80,
je n'immaginais pas qu'elle dépasserait la centaine de pages, ni que 
Perl deviendrait si populaire. Ce document n'aurait pas pu être écrit 
sans l'aide précieuse de Larry Wall et du reste de l'équipe de 
développement de Perl.

=head1 Author and Copyright Information

Copyright (c) 1997, 1998 Tom Christiansen and Nathan Torkington.
All rights reserved.

=head2 Distribution de la documentation 

Lorsqu'elle est fournie comme composante de la distribution standard de
Perl ou de sa documentation imprimée ou sous un autre format, ce travail
doit être distribué selon les termes de la license Artistique de Perl.
Toute autre distribution de ces fichiers ou de ses dérivés en I<dehors> 
de ce paquetage impose qu'un tel arrangement soit fait avec le 
propriétaire du copyright.

Tous les exemples de cette FAQ sont placés dans le domaine public. Vous
êtes autorisé et encouragé à utiliser ce code dans vos propres 
programmes pour le plaisir ou pour le profit comme vous le voulez. Un 
simple commentaire dans le source mentionnant la réutilisation serait 
poli mais n'est pas obligatoire.

=head2 Rappel 

Les informations vous sont offertes de bonne grâce et dans l'espoir 
qu'elles pourront vous servir, mais elles ne sont pas garanties d'être 
correctes, à jours, ou utilisables pour quoique se soit. L'auteur 
n'accepte aucune responsabilité concernant ces informations ni sur leurs 
utilisations.

=head1 TRADUCTION

=head2 Version

Cette traduction française correspond à la version anglaise distribuée avec
perl 5.6.0.  Pour en savoir plus concernant ces traductions, consultez
L<http://perl.enstimac.fr/>.

=head2 Traducteur

Marc Carmier <carmier@immortels.frmug.org>

=head2 Relecture

Pascal Ethvignot <F<pascal@encelade.frmug.org>>
